//base
export const SET_MODULE = "SET_MODULE";
export const SET_NAME = "SET_NAME";

//shop query
export const SET_HOME_PAGE_SHOP_LIST='SET_HOME_PAGE_SHOP_LIST'
export const SET_SEARCH_PAGE_SHOP_LIST='SET_SEARCH_PAGE_SHOP_LIST'
export const SET_SHOP_BY_ID_RESULT='SET_SHOP_BY_ID_RESULT'

//food query
export const SET_SHOP_FOODS_LIST='SET_SHOP_FOODS_LIST'

//cart management
export const SET_CART_LIST='SET_CART_LIST'
export const SET_SHOP_CART_LIST_BY_SHOP_ID='SET_SHOP_CART_LIST_BY_SHOP_ID'
export const CHANGE_CART_UPDATE_FLAG='CHANGE_CART_UPDATE_FLAG'
export const PLUS_CART_ITEM='PLUS_CART_ITEM'
export const MINUS_CART_ITEM='MINUS_CART_ITEM'
export const SET_SHOP_CART_LIST_NULL='SET_SHOP_CART_LIST_NULL'
export const CALCULATE_TOTAL_COST='CALCULATE_TOTAL_COST'

export const CLEAR_TOTAL_COST='CLEAR_TOTAL_COST'

//user address
export const SET_USER_ADDRESS_LIST='SET_USER_ADDRESS_LIST'

//commit order
export const SET_ADDRESS_SELECTED='SET_ADDRESS_SELECTED'
export const SET_COMMIT_FOOD_LIST='SET_COMMIT_FOOD_LIST'

//user order list
export const SET_ORDER_LIST='SET_ORDER_LIST'